spring:
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        
  http: 
    encoding: 
      charset: UTF-8
      enabled: true
      force: true
  datasource.sql-script-encoding: UTF-8
  
logging:
  level:
    org:
      hibernate:
        type: trace
    com:
      alexgaas:
        testcontainersblueprints:
          type: trace

server:
  port: 9090

---
spring:
  profiles: default, testing

  flyway:
    url: jdbc:mariadb://localhost/blueprints?useMysqlMetadata=true&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    schemas: blueprints
    user: root
    password: test
    out-of-order: true
    ignoreMissingMigrations: true

  datasource:
    url: jdbc:mariadb://localhost/blueprints?useUnicode=true&characterEncoding=utf8
    username: root
    password: test

